### ISSUE TITLE
py.test environment is hard to setup properly

### ISSUE THREAD

**Issue by axetwe** [GluuFederation/gluu-flask#10]
I managed to get python tests to run successfully (37 passed in 0.59 seconds), but I had to use this [guide](http://fgimian.github.io/blog/2014/04/20/better-python-version-and-environment-management-with-pyenv/) to setup pyenv instead of virtualenv, under root.

Running it as a normal user causes various errors.

**Comment by nynymike** [comment]
Nice find. Update the README.md if you need to change how to build the virtual env.

**Comment by iromli** [comment]
> I managed to get python tests to run successfully (37 passed in 0.59 seconds), but I had to use this guide to setup pyenv instead of virtualenv, under root.

We don't need pyenv to install gluu-flask. I have setup remote server where it uses Python and virtualenv installed from Ubuntu package manager, and testcases were successfully passed.
