### ISSUE TITLE
Log every 'cmd.run' command verbatim in addition to the description

### ISSUE THREAD

**Issue by axetwe** [GluuFederation/gluu-flask#11]
example from api/setup/ldap_setup.py:

```
self.logger.info("configuring opendj config changes: {}".format(dsconfigCmd))
self.saltlocal.cmd(self.node.id, 'cmd.run', [dsconfigCmd])
```

maybe it should be 'debug' level though. Salt logs it too, but there's a lot of clutter.

**Comment by nynymike** [comment]
Good idea. If we can reduce the operational logs to the bare minimum, this would be great.

**Comment by iromli** [comment]
`cmd.run` might run a sensitive command, hence we chose to log commands selectively.
