### ISSUE TITLE
oxAuth setup

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#13]
These are steps to setup oxAuth node:

* [x] Build gluuoxauth image (if not exist)
* [x] Run the gluuoxauth container
* [x] Setup oxAuth inside the running container
* [x] Update oxauth-ldap.properties when LDAP nodes are created/removed
* [x] Hostname resolution (i.e. hostname_oxauth_cluster should be resolved)

**Comment by iromli** [comment]
There's an error when building gluuoxauth image:

```json
{"errorDetail":{"message":"The command [/bin/sh -c wget -q \"$TOMCAT_DOWNLOAD_URL\" -P /tmp \u0026\u0026 tar -xzf /tmp/apache-tomcat-7.0.57.tar.gz -C /opt \u0026\u0026 rm -f /tmp/apache-tomcat-7.0.57.tar.gz] returned a non-zero code: 8"},"error":"The command [/bin/sh -c wget -q \"$TOMCAT_DOWNLOAD_URL\" -P /tmp \u0026\u0026 tar -xzf /tmp/apache-tomcat-7.0.57.tar.gz -C /opt \u0026\u0026 rm -f /tmp/apache-tomcat-7.0.57.tar.gz] returned a non-zero code: 8"}
```

Apparently, Dockerfile wants to download the non-existant Tomcat (v7.0.57) release. See http://mirrors.advancedhosters.com/apache/tomcat/tomcat-7/ for available releases.

**Comment by shouro** [comment]
FIXED

**Comment by iromli** [comment]
@shouro thanks

**Comment by iromli** [comment]
@shouro we may need to generate oxauth-web-keys.json (OpenID key); but to retrieve this key, we need the prerequisites .jar files (ref: https://github.com/GluuFederation/community-edition-setup/blob/881c967544440d29afac0620e9203d9afb730953/setup.py#L704)
