### ISSUE TITLE
Sometimes there's an exception on removing a node

### ISSUE THREAD

**Issue by axetwe** [GluuFederation/gluu-flask#2]
127.0.0.1 - - [04/Mar/2015 15:23:01] "GET /node HTTP/1.1" 200 -
'NoneType' object has no attribute 'remove_node'
127.0.0.1 - - [04/Mar/2015 15:23:01] "DELETE /node/54f3a1812f74 HTTP/1.1" 200 -
127.0.0.1 - - [04/Mar/2015 15:23:01] "GET /node HTTP/1.1" 200 -

I don't know the reason, but I wrapped it in try/catch so it won't print the whole HTML page on the console.

https://github.com/GluuFederation/gluu-flask/commit/faf04ea8a71a8118ef22a80e6f3b157f93f3c38f

**Comment by iromli** [comment]
`remove_node` is GluuCluster method, so I guess when API tries to fetch the GluuCluster object from database, it can't find it. Perhaps the cluster is already deleted by another process.

We can safely checks whether cluster object is exist before calling `remove_node` (https://github.com/GluuFederation/gluu-flask/blob/1751af1d05835798bf9ccb4aba8473b52e0e3722/api/resource/node.py#L99-L101).

I'll fix it. Thanks for the report.

**Comment by iromli** [comment]
Also, I think we can remove try-catch block and let API fails (returns status code 500) when there's an uncaught error so HTTP client knows that it was our fault.

**Comment by axetwe** [comment]
Sure, as long as it's handled in some way.

**Comment by iromli** [comment]
updated in 59f2209c40a82d52baa94ba27d4da400e2944350
