### ISSUE TITLE
Delete API removes the provider from DB without action

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/gluu-flask#25]
When I run the gluu-flask as a non root user and do not have authorization for deleting provider from salt. I get a error stating internal server error. But the entry for the provider vanishes from the provider list.

**Comment by iromli** [comment]
@tecoholic 

> I get a error stating internal server error

What's the error message?

**Comment by tecoholic** [comment]
IOError: [Errno 13] Permission denied: '/var/cache/salt/master/.dfnt'

This can be fixed by running the API server as root. I am not much worried about the error here. The thing is, the entry is removed from the database, even when the salt throws this error at me.

**Comment by shouro** [comment]
It is not an issue. First of all do not run gluu-flask other than root. It
is designed
to run only under root. How it behave under non root access is out of scope.

On Jun 13, 2015 8:18 AM, "Arunmozhi" <notifications@github.com> wrote:
>
>  IOError: [Errno 13] Permission denied: '/var/cache/salt/master/.dfnt'
>
> This can be fixed by running the API server as root. I am not much
worried about the error here. The thing is, the entry is removed from the
database, even when the salt throws this error at me.

**Comment by tecoholic** [comment]
> How it behave under non root access is out of scope.

Hence, closing the issue.
