### ISSUE TITLE
Add gluu-flask policy to limit Providers to the number specified in the property license_count_limit

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-flask#28]
Yuriy Z is adding a new license property called "providerCount" with a default value of 1, which will be sold via ecommerce. Licenses with a high providerCount will have to be custom issued by Gluu staff.

**Comment by yuriyz** [comment]
providerCount -> license_count_limit

**Comment by iromli** [comment]
@nynymike registering a _consumer_ provider requires unique license retrieved from license server. I believe license server will not generate new license if `license_count_limit` is exceeded. It's worth noting that there's 1:1 mapping between license:consumer_provider. This has been addressed by current codebase.

**Comment by iromli** [comment]
What I was trying to say is, one cannot register _consumer_ provider without having a valid license.

**Comment by iromli** [comment]
This feature has been landed in v0.2
