### ISSUE TITLE
Rethink/Combine License Keys and Licenses

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/gluu-flask#29]
I feel having two entities to manage a license in the current state is redundant. The license object currently(v0.2) takes just  the ID of license key as its input parameter and nothing else. With the current policy of having a single license key per cluster, this redundancy is even more imposing.

**Comment by tecoholic** [comment]
Also as an extension to this thinking, If we are going to impose a one license-per-cluster policy, then we can do away with asking the admin to input license id as an parameter when creating new Providers also.

**Comment by iromli** [comment]
The feature is merged into `master` branch
