### ISSUE TITLE
404 responses in the API

### ISSUE THREAD

**Issue by axetwe** [GluuFederation/gluu-flask#3]
API specifies 404 responses for invalid GET requests, but no 404 responses for invalid DELETE requests.

**Comment by iromli** [comment]
I saw that you have modified Node resource so it returns 404 response when node is not exist. Do you think we should treat Cluster resource to return 404 response when cluster is not found upon deletion?

In https://github.com/GluuFederation/gluu-flask/blob/1751af1d05835798bf9ccb4aba8473b52e0e3722/api/resource/cluster.py#L58, any delete operation returns 204 response regardless the cluster existence in database.

**Comment by axetwe** [comment]
Yes, I think that if item is 'not found' for non-creating operation it should return 404.

http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by iromli** [comment]
ok, I'll fix it

**Comment by iromli** [comment]
updated in 5a0606fc3acb6dd15dc6383ea2c65b3b37b12dca
