### ISSUE TITLE
Node deployment log filenames should match node names

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/gluu-flask#30]
Since the only time the deployment log is being dealt with is during the node creation process and hence for later retrieval of deployment log for a node, it would be simpler if the node log filename matches the node's name. That way we still have unique file names and also access it with ease.

**Comment by iromli** [comment]
@tecoholic this feature is merged to master at https://github.com/GluuFederation/gluu-flask/commit/cdaf8415c6259f842fcf4aed2d5ee0e4daac0da2
