### ISSUE TITLE
Only allow 1 oxTrust node in cluster

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#34]
Due to cache refresh, cluster must permit 1 oxTrust instance (should be deployed in master provider).

**Comment by iromli** [comment]
Fixed in b1eb592fdeb96c32dd89f454ee7241fdb00fd2f0

**Comment by yurem** [comment]
In oxTrust it's possible which server should run CR. In appliance entry there is attribute oxTrustCacheRefreshServerIpAddress which allows to specify which oxTrust instance should run CR.

**Comment by iromli** [comment]
@yurem noted; we will take a look again in the future; for current version, @nynymike wanted a single oxtrust instance per cluster. 

Thanks.

**Comment by nynymike** [comment]
Yura, I didn't remember that we had this feature. I just added a comment to https://github.com/GluuFederation/community-edition-setup/commit/6cfc707831348a23ceef34b9dcaaccbf19cba592 

Let's leave it for now. We don't have the time to test clustered oxTrust right now.
