### ISSUE TITLE
push custom schema file in opendj container

### ISSUE THREAD

**Issue by shouro** [GluuFederation/gluu-flask#38]
We will put custom schema file in some fixed predefine path in master. gluu-flask will put this file in opendj container using salt when it create pendj container. if path is empty it will do nothing, same name file will be overwritten, it will copy all schema file from this path.
proposed path: /opt/custom/opendj/schema

**Comment by iromli** [comment]
I suggest we use `/etc/gluu/ldap` instead of `/opt/custom`, as we already have `/etc/gluu/prometheus` and `/etc/gluu/saml`

**Comment by shouro** [comment]
but /etc is the place for configuration, we can put oxauth custom configuration unter /etc but i think we cant put ldap schema here.

**Comment by iromli** [comment]
perhaps we can use `/opt/gluu/ldap/*`

**Comment by nynymike** [comment]
I agree with shouro... its a little weird to but it in /opt ... normally /opt is for third party software.

**Comment by iromli** [comment]
I've been tinkering with the code and decided to put custom LDAP schema to `/var/lib/gluu-cluster/custom/opendj/schema`. If we're agree on this path, I can merge the code to the upcoming release. If not, any suggestion where we should put the custom schema to?

**Comment by shouro** [comment]
Mike, we failed to find any other better option to put custom schemas in filesystem.
So I think /opt/gluu will be our default location and we will create out own filesystem hierarchy here.

**Comment by nynymike** [comment]
I don't think /var/lib is correct. This folder is used to perform "state information to preserve the condition of an application between different instances of the same application." So this fits perfectly.... we need each instance of opendj to have the same schema. If you also consider something like the asterisk phone system, which uses /var/lib/asterisk to store the voice prompts, it makes sense too. The only thing that I can say for sure is that putting this data in /opt is clearly incorrect.

**Comment by iromli** [comment]
@nynymike I'm afraid I don't fully understand between

> I don't think /var/lib is correct

and

> So this fits perfectly.... we need each instance of opendj to have the same schema. If you also consider something like the asterisk phone system, which uses /var/lib/asterisk to store the voice prompts, it makes sense too.

Were you agree or disagree to put the custom schema in `/var/lib` ?

**Comment by iromli** [comment]
I decided to put the custom schema at `/var/lib/gluu-cluster/custom/opendj/schema`. Feel free to re-open this issue if there's any objection. Closing ...
