### ISSUE TITLE
Problem with restart policy

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#41]
I've been trying to use docker restart policy set to `always`.

When VM rebooted or docker daemon restarted, I saw all nodes are restarting themselves.
Combined with our gluu-agent init script, weave IP and all nodes setup were properly restored.
However, when I visited Idp page (`/oxauth`), gluuhttpd node returned 503/403 status code.

After digging httpd error.log, I've found that gluuoxauth aren't running properly. The tomcat process that listens on port 8009 weren't running at all. Digging to gluuoxauth's `localhost.log`, I found there's an error in LDAP connection even when gluuopendj node is running.

My guess is when gluuoxauth trying to connect to gluuopendj, weave IP routing wasn't ready yet, hence gluuoxauth failed to make a connection. When I stopped gluuoxauth and then run gluu-agent init script manually, gluuoxauth were restored properly.

If we want to use restart policy, I guess we need to make sure the order of restarted nodes in following order:

1. weave
2. gluuopendj
3. gluuoxauth
4. gluuhttpd
5. gluuoxtrust
6. prometheus

On the other hands, gluu-agent init script I've been working on ensures the order of restarted nodes even without restart policy.
Ideally, we should find a way on how to combine docker restart policy and gluu-agent init script.

**Comment by iromli** [comment]
@shouro any idea?

**Comment by nynymike** [comment]
Its a good question... solaris used to deal with startup dependencies better than Linux using [SMF scripts](https://en.wikipedia.org/wiki/Service_Management_Facility) Quick google search turned up [Monit](https://mmonit.com/monit/)

**Comment by iromli** [comment]
A tool that can ensure the order of running process is what we need. After few tests, I'm sure docker policy restart doesn't fit our usecase.

On the other hands, the introduction of supervisord entry in our containers simplify the gluu-agent itself. I've tried the supervisord addition made by @shouro and modified gluu-agent. This combination brings back the provider + nodes properly.

**Comment by shouro** [comment]
why gluuoxauth crashed when it failed to find opendj, it should ping
periodically or check upon request and wait until it finds a database, this
should be basic thing in every server.
the main idea was start node using docker restart policy it will not care
about weave on boot sequence, then all the service will wait for weave
routing to come up (recovery script will restore it).
For example when a flask app or my old chat app running in tomcat failed to
connect a database will it crash? No, it gives some error or message and
wait for the database to come online.
It is unacceptable if our services cant handle it. If this is the case we
must fix it now.

**Comment by iromli** [comment]
> For example when a flask app or my old chat app running in tomcat failed to connect a database will it crash? No, it gives some error or message and wait for the database to come online.

I guess it depends on how the app is written.

> why gluuoxauth crashed when it failed to find opendj, it should ping periodically or check upon request and wait until it finds a database, this should be basic thing in every server.

> It is unacceptable if our services cant handle it. If this is the case we must fix it now.

Better to ask oxAuth developers then.

**Comment by nynymike** [comment]
@shouro Any feature requests wouldn't go into the code until 2.4.1... so if you want a solution, you'll need to make it work with 2.3.4...

**Comment by iromli** [comment]
We can postpone restart policy. Recovery script will restart the container manually.

**Comment by shouro** [comment]
@iromli agreed

**Comment by iromli** [comment]
Restart policy is postponed. We have our own recovery script that manage the order of container restarts.
