### ISSUE TITLE
Create Log with equivalent curl commands

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-flask#57]
It would be really cool if we had a config-history.log file that provided that provided a log of what happened in the web UI, rendered as curl commands. This would enable an admin to use the GUI for configuration, but to look at the log for the equivalent curl commands, possible to use in scripting.

**Comment by shouro** [comment]
I think gluuapi.log does this already.

On Tue, Dec 22, 2015 at 3:03 AM, Mike Schwartz <notifications@github.com>
wrote:

> It would be really cool if we had a config-history.log file that provided
> that provided a log of what happened in the web UI, rendered as curl
> commands. This would enable an admin to use the GUI for configuration, but
> to look at the log for the equivalent curl commands, possible to use in
> scripting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GluuFederation/gluu-flask/issues/57>.
>



-- 
$ whatis themeaningoflife
$ themeaningoflife: nothing appropriate

http://shouro.blogspot.com

**Comment by iromli** [comment]
> I think gluuapi.log does this already.

No, it's different kind of log. gluuapi.log only logs request (similar to Apache/nginx log) and apps log. It doesn't record the "curl" command

**Comment by iromli** [comment]
I think this issue should be moved to https://github.com/GluuFederation/gluu-webui/
