### ISSUE TITLE
Replace daemonocle

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#59]
One of the reasons why we need to replace [daemonocle](https://github.com/jnrbsn/daemonocle) is, the library uses pinned dependencies on packaging, as seen on its [setup.py](https://github.com/jnrbsn/daemonocle/blob/519cdf1fe43a63fe8c0e44efabdbe0a8058b7623/setup.py#L28-L29). It's difficult to maintain compatibility with other libraries (for example, most distribution will ship newer [click](http://click.pocoo.org/5/) library) as daemonocle holding us back.

**Comment by iromli** [comment]
> It's difficult to maintain compatibility with other libraries (for example, most distribution will ship newer click library

For example, in our CentOS repo, `click` version is above v2.5 (the one that required by `daemonocle`).

**Comment by shouro** [comment]
I used supervisor to start and stop a flask app.
```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello Gluu!\n"

if __name__ == "__main__":
    app.run()
```
and this is my supervisord.conf file:
```
[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=10MB
logfile_backups=2
loglevel=error ; info, debug, warn, trace
pidfile=/var/run/supervisord.pid
user=root
childlogdir=/var/log/supervisor/

[program:gluuflask]
command=python /home/ubuntu/run.py
user=ubuntu
```
we can use this to start restart and stop gluu-flask:
```
supervisorctl start gluuflask
supervisorctl stop gluuflask
supervisorctl restart gluuflask
```
I think we can try it.

**Comment by iromli** [comment]
The new daemonocle release fixed this issue.
