### ISSUE TITLE
Set max. file descriptor for gluuopendj container

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#64]
Reference: https://backstage.forgerock.com/#!/docs/opendj/2.6.0/release-notes/chap-before-you-install#prerequisites-file-descriptors

**Comment by nynymike** [comment]
I'm not sure this can be done in the container. I think it needs to be done on the host system.

**Comment by ganesh-at-wiw** [comment]
Here is a solution which I tested in local VM.

Add the file: /opt/gluu-server-{whateverversion}/etc/sysctl.conf

Then running: /sbin/sysctl -p /opt/gluu-server-{whateverversion}/etc/sysctl.conf

from inside of /etc/init.d/gluu-server-{whateverversion} makes the value effective at system level and leaves the host system intact.

**Comment by iromli** [comment]
> I'm not sure this can be done in the container

It's possible to set ulimit inside the container (https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container-ulimit).

**Comment by iromli** [comment]
@nynymike out of curiosity, do oxAuth or oxTrust has recommended max. file descriptor? /cc @yurem

**Comment by iromli** [comment]
Merged to `master` branch
