### ISSUE TITLE
docker-machine integration

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#65]
By using docker-machine, we can spawn providers faster. Also, there's a possibility we can use docker-machine to replace salt-master and salt-minion (which is sometimes raises problems with its delay time when executing remote commands).

**Comment by iromli** [comment]
I found that some docker-machine (v0.6) commands (e.g. `docker-machine ls`) with _generic driver_ are buggy when target machine is CentOS. I will investigate this issue.

**Comment by iromli** [comment]
Here's an example:

```
$ docker-machine ls
NAME             ACTIVE   DRIVER    STATE     URL                       SWARM   DOCKER    ERRORS
gluu-consumer    -        generic   Running   tcp://172.20.20.11:2376           Unknown   Unable to query docker version: Get https://172.20.20.11:2376/v1.15/version: dial tcp 172.20.20.11:2376: getsockopt: no route to host
gluu-consumer2   -        generic   Running   tcp://172.20.20.12:2376           v1.10.1   

```

`gluu-consumer` is CentOS-based machine, while `gluu-consumer2` is an Ubuntu-based machine. Notice, that docker-machine unable to query docker engine in `gluu-consumer` machine, though docker engine was installed and running in that machine.

**Comment by nynymike** [comment]
I don't think we should support mixed enviornments, if that helps.

**Comment by iromli** [comment]
> I don't think we should support mixed enviornments, if that helps.

Yes, a cluster should use same environment (Ubuntu/CentOS).

I'm worrying about the upcoming CentOS support (if we going to use docker-machine). Need to investigate how to make all docker-machine commands work in CentOS. Ubuntu support works like a charm though.

**Comment by iromli** [comment]
Just tested on CentOS hosted at DigitalOcean. It works! I guess there's network or SSH issue with my testing machines.

**Comment by shouro** [comment]
# Docker + swarm + weave + docker-machine
For simplicity I use docker hub discovery, we need to use consul in production

## Commands:

$ docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery token://xxx \
    swarm-master

$ docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-discovery token://xxx \
    slave-1

$ docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-discovery token://xxx \
    slave-2


$ docker-machine ssh swarm-master "sudo curl -L git.io/weave -o /usr/local/bin/weave"
$ docker-machine ssh swarm-master "sudo chmod +x /usr/local/bin/weave"

$ docker-machine ssh slave-1 "sudo curl -L git.io/weave -o /usr/local/bin/weave"
$ docker-machine ssh slave-1 "sudo chmod +x /usr/local/bin/weave"

$ docker-machine ssh slave-2 "sudo curl -L git.io/weave -o /usr/local/bin/weave"
$ docker-machine ssh slave-2 "sudo chmod +x /usr/local/bin/weave"

docker-machine ssh swarm-master weave launch
docker-machine ssh slave-1 weave launch $(docker-machine ip swarm-master)
docker-machine ssh slave-2 weave launch $(docker-machine ip swarm-master)

$ eval $(docker-machine env --swarm swarm-master)

$ docker run --net=weave -h foo.weave.local --name=foo $(weave dns-args) -it ubuntu bash
$ docker run --net=weave -h bar.weave.local --name=bar $(weave dns-args) -it ubuntu bash
$ docker run --net=weave -h baz.weave.local --name=baz $(weave dns-args) -it ubuntu bash

themonk@redqueen:~$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
3a9bb1801de3        ubuntu                       "bash"                   4 minutes ago       Up 4 minutes                            slave-1/baz
9b4d705dfef4        ubuntu                       "bash"                   12 minutes ago      Up 12 minutes                           swarm-master/bar
64cdf64de44a        ubuntu                       "bash"                   13 minutes ago      Up 13 minutes                           slave-2/foo
.....

**Comment by iromli** [comment]
We have docker-machine integration to create host for generic and digitalocean drivers now. It's in `master` branch.

**Comment by oluies** [comment]
@iromli is there an example for the generic one for local swarm ? Could I adapt it for the non machine (docker for mac)

**Comment by iromli** [comment]
@oluies We had never test the swarm in generic driver. Also, i'm not sure about "non machine" as gluu-engine uses docker-machine under the hood.

Most of our tests are running using digitalocean (and sometime amazonec2) driver, so I'm not sure about generic driver now. I can take a look later though.
