### ISSUE TITLE
docker-engine from official repo

### ISSUE THREAD

**Issue by shouro** [GluuFederation/gluu-flask#68]
Available docker-engine versions:
$ apt-cache madison docker-engine

We can install any docker-engine version:
$ apt-get install docker-engine=1.9.1-0~trusty

I guess this will save us from maintaining our own deb pkg.

**Comment by iromli** [comment]
> I guess this will save us from maintaining our own deb pkg.

Yes, I agree.

**Comment by iromli** [comment]
Closing this issue as it's not related to this project directly. `docker-engine` dependency is taken care by `gluu-master` package. I will notify @adrian-gluu about the changes in upcoming release.
