### ISSUE TITLE
Non-blocking response for node deletion

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#69]
Currently, node deletion blocks the main thread, hence any API call will have to wait for completed deletion. In turns, web UI will be affected (not responding). My idea is to return the response immediately just like node creation, and provide a log for deletion process.

**Comment by shouro** [comment]
+1

**Comment by nynymike** [comment]
yes, definitely.

**Comment by iromli** [comment]
Fixed in v0.4.3+
