### ISSUE TITLE
API to customize oxauth / oxtrust war file

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-flask#72]
If customers need to change a file in the war distribution of oxauth or oxtrust, they must do this by uploading a file and a full path for the file via an API. The API server should store this file, and the local and remote path for the file, and then push it out to the oxauth|oxtrust instances in the cluster.

**Comment by iromli** [comment]
What if we don't provide API for upload? Instead we provide predefined path to store custom files for oxauth/oxtrust. 

For example, let's say we have`/var/lib/gluu-cluster/custom/oxauth` directory. If we store a file inside the directory, e.g. `/var/lib/gluu-cluster/custom/oxauth/opt/tomcat/webapps/oxauth/login.xhtml`, this file will be distributed as `/opt/tomcat/webapps/oxauth/login.xhtml` to all oxauth nodes in the cluster. We can use filesystem event to monitor changes and re-distribute the file.

**Comment by iromli** [comment]
First layer of this feature has been merged to `master` branch. This layer monitors filesystem changes in predefined directory; which will be copied to all oxAuth/oxTrust containers. The idea is simply taken from existing oxIdp filesystem events.

Next step will be deciding whether we need to provide HTTP API or not.

**Comment by iromli** [comment]
@shouro I think we need to backport this feature to 0.4 since releasing 0.5 with all new features will take more time.

**Comment by iromli** [comment]
There's a problem with salt copy_file. During my test, i couldn't transfer file higher than 4MB. I saw the salt event for file copy operation is done, however I couldn't find any copied file in the containers.

**Comment by nynymike** [comment]
maybe we make the file available via the API, and then remotely execute a command on the target server to wget it...

**Comment by iromli** [comment]
I will re-testing the implementation as we have new codebase that uses docker native commands.

**Comment by iromli** [comment]
Tested and fixed to conform to latest codebase.
