### ISSUE TITLE
Node is not saved to database

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#77]
After creating machine, node is not saved on first try. `docker-machine ls` returns correct info though:
```
» docker-machine ls
NAME             ACTIVE   DRIVER    STATE     URL                       SWARM                  DOCKER    ERRORS
gluu-master      -        generic   Running   tcp://172.10.10.11:2376   gluu-master (master)   v1.11.0   
gluu.discovery   -        generic   Running   tcp://172.10.10.10:2376                          v1.11.0
```

Also, all `consul` and `swarm` containers are running inside the machines.

```
root@gluu-discovery:/home/vagrant# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                            NAMES
e4c9b68ddf34        progrium/consul     "/bin/start -server -"   9 minutes ago       Up 9 minutes        53/tcp, 53/udp, 8300-8302/tcp, 8400/tcp, 8301-8302/udp, 0.0.0.0:8500->8500/tcp   consul
```

```
root@gluu-master:/home/vagrant# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
c4a707853301        swarm:latest        "/swarm join --advert"   4 minutes ago       Up 4 minutes                            swarm-agent
096496cdecee        swarm:latest        "/swarm manage --tlsv"   4 minutes ago       Up 4 minutes                            swarm-agent-master
```

on second attempt, all nodes are saved successfully.

**Comment by iromli** [comment]
Trying to reproduce the issue for the 3rd time, only discovery node is saved to database.

**Comment by iromli** [comment]
For some unknown reason (there's no log I can see), master machine is deleted right after creating it. Perhaps this is why the node is not saved to database.

**Comment by shouro** [comment]
I never get this problem. Every time all nodes are saved.

**Comment by iromli** [comment]
This issue affects generic driver.

**Comment by shouro** [comment]
only generic?

**Comment by iromli** [comment]
Yes. The strange thing is, it's sometime work, sometime doesn't. I think if we have logs about node creation, we can inspect the problem better.

**Comment by iromli** [comment]
> The strange thing is, it's sometime work, sometime doesn't.

On my 4th attempt, all nodes are saved successfully.

**Comment by iromli** [comment]
@shouro One way to reproduce this issue is by re-using VM for generic machine.

1. Create a generic machine. Node will be saved successfully.
2. Remove this generic node (and machine). Note, this won't remove VM including it's docker images and containers.
3. Re-create a generic machine using same VM. This time node won't be saved because there's error when running container. I think we should check whether container is already running or not.

So far this is what I've found. Re-using same VM for generic node might be a bad idea.

**Comment by iromli** [comment]
Node is properly saved to database now.
