### ISSUE TITLE
Guard againsts duplicate machine name

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#78]
Currently, duplicate machine name will be rejected. However, this will also deletes existing machine.

To reproduce this issue:

1. Create a node called `gluu-master`.
2. Re-create another called with same `gluu-master` name. An error response will be returned: `{"message": "return code 1: Host already exists: \"gluu-master\"",  "status": 500}`. Eventually, the existing `gluu-master` machine will be deleted. This could be a problem when we have containers inside the machine.

The problematic line is found [here](https://github.com/GluuFederation/gluu-flask/blob/c11dd6915afdd11774127e0e8a97e17e27ec41ee/gluuapi/resource/node.py#L135).

**Comment by iromli** [comment]
I think this is related to #77. Since the node is not saved to database yet, on of the rules in `validate_name` method in `gluuapi.reqparser.node` returns false.

```python
if db.count_from_table('nodes', db.where('name') == value):
    raise ValidationError("name is already taken")
```

**Comment by shouro** [comment]
Hmm i will look into this.

**Comment by iromli** [comment]
Node's name is unique now.
