### ISSUE TITLE
Copy generated SAML config to oxIDP containers

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#79]
In our new cluster setup, the host where oxTrust container is deployed to (master host), is not always the same host where API lives (control host). As a result, the `OxidpWatcher` task may not work since it can't monitor file changes in `/var/lib/gluu-cluster/override/oxidp` inside master host.

One of the solutions is to extract `OxidpWatcher` task as a standalone program and install it into master host. Another solution is to make `OxidpWatcher` task as part of `gluu-agent` library.

**Comment by shouro** [comment]
we can terget node when we deploy oxtrust
here is the example:
docker run -d --name=web1 -h web1 --env="constraint:node==master-node" tutum/hello-world

**Comment by iromli** [comment]
> we can terget node when we deploy oxtrust

The constraint is already implemented.

> As a result, the OxidpWatcher task may not work since it can't monitor file changes in /var/lib/gluu-cluster/override/oxidp inside master host.

This issue only happened when control and master host is not a same host. It means `OxidpWatcher` which runs in control host cannot monitor files in master or any remote host.

**Comment by shouro** [comment]
got it :)

**Comment by iromli** [comment]
@shouro the workaround requires https://github.com/GluuFederation/cluster-tools/blob/master/fswatcher.py running as daemon in master node.
