### ISSUE TITLE
Node creation takes too long which hampers testing

### ISSUE THREAD

**Issue by axetwe** [GluuFederation/gluu-flask#9]
Most of prep and configuration should be moved to the Dockerfile, docker images should be parameterised.

**Comment by shouro** [comment]
may be we can use this in pytest to solve it, http://flask.pocoo.org/docs/0.10/signals

**Comment by iromli** [comment]
Currently we're using pytest monkeypatch to cut off network calls executed by salt and docker. We'll stick with this approach until we found a better approach.
